trigger:
- master
pr:
- master
jobs:
  - job: CI
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          yarn install
          yarn run build
        displayName: 'yarn install and build'

  - job: Publish
    dependsOn: CI
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          yarn install
          yarn run build
        displayName: 'yarn install and build'
      - script: NPM_AUTH_TOKEN="$(NPM_AUTH_TOKEN)" node ./bin/publish.js
        displayName: 'Package and publish to npm'
